// Generated by CoffeeScript 1.12.4
var NLP, colors, franc;

franc = require('franc');

colors = require('colors');

NLP = {
  detectLanguage: function(options) {
    return new Promise(function(resolve, reject) {
      return resolve({
        lang: franc(options.text)
      });
    });
  }
};

module.exports = NLP;
